### ISSUE TITLE
Bind mount volumes when using isoSegmenter inside docker container

### ISSUE THREAD

**Issue by diazcastillo** [bunop/isoSegmenter#3]
Hello,
I am trying to make isoSegmenter in my computer but have no success yet. I succesfully installed isoSegmenter using Docker, and I am able of retrieving isoSegmenter.py help message. However, I tried running your suggested test and got the following response: 

isoSegmenter.py --infile test/chr21.fa.gz --outfile chr21.isochores.csv --graphfile chr21.isochores.png --draw_legend

No handlers could be found for logger "GClib.Graphs"
2020-07-14 21:59:29,762 - isoSegmenter.py - INFO - 

isoSegmenter  Copyright (C) 2013-2019 ITB - CNR
This program comes with ABSOLUTELY NO WARRANTY; for details type:

    `isoSegmenter.py --help'.

This is free software, and you are welcome to redistribute it
under certain conditions; show LICENSE.md for more details.

2020-07-14 21:59:29,762 - GClib.Utility - INFO - Opening test/chr21.fa.gz...
Traceback (most recent call last):
  File "/usr/local/bin/isoSegmenter.py", line 253, in <module>
    FastaFile = Utility.FastaFile(args.infile)
  File "/usr/local/lib/python2.7/site-packages/GClib/Utility.py", line 65, in __init__
    self.Load(fasta_file)
  File "/usr/local/lib/python2.7/site-packages/GClib/Utility.py", line 78, in Load
    fasta_fh = gzip.open(fasta_file, "rb")
  File "/usr/local/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/local/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: 'test/chr21.fa.gz'

Is there anything else I have to do to make isoSegmenter run?
Thanks for the help
Carlos

**Comment by bunop** [comment]
Hi @diazcastillo,

Thank you for your interest in `isoSegmenter`, Regarding your question, the reason which it doesn't work as expected is in the last line of the error message, there isn't such file in docker container:

> OError: [Errno 2] No such file or directory: 'test/chr21.fa.gz'

In order to use `isoSegmenter` with real data, you need to [bind mount](https://docs.docker.com/storage/bind-mounts/) the folder which contains data inside the container. Even results need to be placed in a **binded folder**, or otherwise you will not able to see such files outside container. For example, to run the same example line of the documentation, you can do like this:
```bash
git clone https://github.com/bunop/isoSegmenter.git
cd isoSegmenter/
docker run -ti --volume $PWD:/data/ bunop/isosegmenter /bin/bash
# next line need to be executed inside docker container
isoSegmenter.py --infile test/chr21.fa.gz --outfile chr21.isochores.csv --graphfile chr21.isochores.png --draw_legend
```
In this case, I've mounted the `isoSegmenter` folder (which contains the `test/chr21.fa.gz` file) inside the container `/data/` volume. Since input and outputs are relative to this path, you will found outputs file inside `isoSegmenter` folder. You will need to mount input and output folder while starting docker container (you can bind multiple directories, please remember mounting using absolute paths). 

Hope this helps

**Comment by diazcastillo** [comment]
Thanks a lot Paolo. It all worked fine.
Carlos
